development:
  adapter: postgresql
  database: database_development
  pool: 5
  timeout: 5000
  host: localhost
test:
  adapter: postgresql
  database: database_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: database_production
  pool: 5
  timeout: 5000
  host: localhost